#SPDX-License-Identifier: MIT-0
---
# tasks file for Nginx
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Remove default Nginx virtual host (Ubuntu specific)
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Create DocumentRoot directories for vhosts
  ansible.builtin.file:
    path: "/var/www/{{ item }}"
    state: directory
    owner: iadiyanov
    group: iadiyanov
    mode: '0755'
  loop: "{{ sites }}"

- name: Create index.html from template
  ansible.builtin.template:
    src: 'index.html.j2'
    dest: "/var/www/{{ item }}/index.html"
    owner: iadiyanov
    group: iadiyanov
    mode: '0644'
  loop: "{{ sites }}"

- name: Copy nginx config from template
  ansible.builtin.template:
    src: 'site.conf.j2'
    dest: '/etc/nginx/conf.d/site-{{ item }}.conf'
    owner: root
    group: root
    mode: '0644'
  loop: '{{ sites }}'
  notify: restart nginx

- name: Ensure Nginx is started and enabled on boot
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
